node {
    git url: 'https://github.com/afym/springboot-application-ci.git'

}

pipeline {
    agent any

    stages {
        stage('Build application') {
            steps {
                sh "docker-compose -f docker-build.yml up"
            }
        }
    }
}