// create hidden parameter : ARTIFACTORY_DIRECTORY = /var/lib/jenkins/workspace/application-build
// create credentials user/pass with the id dockerhub (docker hub credentials)
pipeline {
    agent any
    stages {
        stage('Test application') {
            steps {
                sh "cd ${params.ARTIFACTORY_DIRECTORY} && docker-compose -f docker-test.yml up"
            }
        }

    stage('Build local image') {
        steps {
            sh "cd ${params.ARTIFACTORY_DIRECTORY} && chmod +x scripts/buil-image.sh && ./scripts/buil-image.sh"
        }
    }

    stage('Publish image') {
        steps {
            withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
                sh "cd ${params.ARTIFACTORY_DIRECTORY} && docker push angelfym/springboot-application-ci:latest"
            }
        }
    }    
    }
}